// This file is auto-generated by scripts/generate-icon-index.js
// Do not edit this file manually!

import { createIcon } from '../createIcon'; // Import the wrapper
import type { IconProps } from '../createIcon'; // Import the props type

import PlaceholderSvg from './Placeholder';

export const PlaceholderIcon = createIcon(PlaceholderSvg);

export type { IconProps };
